/*	Merge additional variables from MO_SUM with Snapshot data  */

%Macro Merge2_MoSum(LOB);
	proc sql;
	create table  &LOB._master_data_3 as select
		t1.*
		,Coalesce(t2.AMT_INS_0,t2.AMT_INS_m1) as &LOB._AMT_INS_SE
/*		,Coalesce(t2.AVG_BAL_0,t2.AVG_BAL_m1) as &LOB._AVG_BAL_SE*/
		,Coalesce(t2.AVG_BLDG_SIZE_0,t2.AVG_BLDG_SIZE_m1) as &LOB._AVG_BLDG_SIZE_SE
		,Coalesce(t2.BAD_TRADE_RATIO_0,t2.BAD_TRADE_RATIO_m1) as &LOB._BAD_TRADE_RATIO_SE
		,Coalesce(t2.BAL_90_0,t2.BAL_90_m1) as &LOB._BAL_90_SE
		,Coalesce(t2.BAL_REG_TL_0,t2.BAL_REG_TL_m1) as &LOB._BAL_REG_TL_SE
		,Coalesce(t2.BLDG_ONLY_IND_0,t2.BLDG_ONLY_IND_m1) as &LOB._BLDG_ONLY_IND_SE
		,Coalesce(t2.EMP_SIZE_CD_0,t2.EMP_SIZE_CD_m1) as &LOB._EMP_SIZE_CD_SE
		,Coalesce(t2.LATE_RATIO_0,t2.LATE_RATIO_m1) as &LOB._LATE_RATIO_SE
		,Coalesce(t2.LOB_CD_0,t2.LOB_CD_m1) as &LOB._LOB_CD_SE
		,Coalesce(t2.NAICS_CD_0,t2.NAICS_CD_m1) as &LOB._NAICS_CD_SE
		,Coalesce(t2.NBR_CLS_0,t2.NBR_CLS_m1) as &LOB._NBR_CLS_SE
		,Coalesce(t2.NEW_PKG_IND_0,t2.NEW_PKG_IND_m1) as &LOB._NEW_PKG_IND_SE
/*		,Coalesce(t2.PKG_IND_0,t2.PKG_IND_m1) as &LOB._PKG_IND_SE*/
		,Coalesce(t2.POLICY_AGE_0,t2.POLICY_AGE_m1) as &LOB._POLICY_AGE_SE
		,Coalesce(t2.PREMOPS_IND_0,t2.PREMOPS_IND_m1) as &LOB._PREMOPS_IND_SE
		,Coalesce(t2.PREV_1YR_CLAIM_CNT_0,t2.PREV_1YR_CLAIM_CNT_m1) as &LOB._PREV_1YR_CLAIM_CNT_SE
		,Coalesce(t2.PREV_1YR_LOSS_AMT_0,t2.PREV_1YR_LOSS_AMT_m1) as &LOB._PREV_1YR_LOSS_AMT_SE
		,Coalesce(t2.PREV_1YR_NB_CLAIM_CNT_0,t2.PREV_1YR_NB_CLAIM_CNT_m1) as &LOB._PREV_1YR_NB_CLAIM_CNT_SE
		,Coalesce(t2.PREV_1YR_PRM_AMT_0,t2.PREV_1YR_PRM_AMT_m1) as &LOB._PREV_1YR_PRM_AMT_SE
		,Coalesce(t2.PREV_2YR_CLAIM_CNT_0,t2.PREV_2YR_CLAIM_CNT_m1) as &LOB._PREV_2YR_CLAIM_CNT_SE
		,Coalesce(t2.PREV_2YR_LOSS_AMT_0,t2.PREV_2YR_LOSS_AMT_m1) as &LOB._PREV_2YR_LOSS_AMT_SE
		,Coalesce(t2.PREV_2YR_NB_CLAIM_CNT_0,t2.PREV_2YR_NB_CLAIM_CNT_m1) as &LOB._PREV_2YR_NB_CLAIM_CNT_SE
		,Coalesce(t2.PREV_2YR_PRM_AMT_0,t2.PREV_2YR_PRM_AMT_m1) as &LOB._PREV_2YR_PRM_AMT_SE
		,Coalesce(t2.PREV_3YR_CLAIM_CNT_0,t2.PREV_3YR_CLAIM_CNT_m1) as &LOB._PREV_3YR_CLAIM_CNT_SE
		,Coalesce(t2.PREV_3YR_FIRE_IND_0,t2.PREV_3YR_FIRE_IND_m1) as &LOB._PREV_3YR_FIRE_IND_SE
		,Coalesce(t2.PREV_3YR_GL_CLAIM_CNT_0,t2.PREV_3YR_GL_CLAIM_CNT_m1) as &LOB._PREV_3YR_GL_CLAIM_CNT_SE
		,Coalesce(t2.PREV_3YR_GL_PRM_AMT_0,t2.PREV_3YR_GL_PRM_AMT_m1) as &LOB._PREV_3YR_GL_PRM_AMT_SE
		,Coalesce(t2.PREV_3YR_LOSS_AMT_0,t2.PREV_3YR_LOSS_AMT_m1) as &LOB._PREV_3YR_LOSS_AMT_SE
		,Coalesce(t2.PREV_3YR_NB_CLAIM_CNT_0,t2.PREV_3YR_NB_CLAIM_CNT_m1) as &LOB._PREV_3YR_NB_CLAIM_CNT_SE
		,Coalesce(t2.PREV_3YR_PRM_AMT_0,t2.PREV_3YR_PRM_AMT_m1) as &LOB._PREV_3YR_PRM_AMT_SE
		,Coalesce(t2.PREV_3YR_PROP_LOSS_AMT_0,t2.PREV_3YR_PROP_LOSS_AMT_m1) as &LOB._PREV_3YR_PROP_LOSS_AMT_SE
		,Coalesce(t2.PREV_3YR_PROP_PRM_AMT_0,t2.PREV_3YR_PROP_PRM_AMT_m1) as &LOB._PREV_3YR_PROP_PRM_AMT_SE
		,Coalesce(t2.PREV_3YR_THEFT_IND_0,t2.PREV_3YR_THEFT_IND_m1) as &LOB._PREV_3YR_THEFT_IND_SE
		,Coalesce(t2.PREV_3YR_WATER_IND_0,t2.PREV_3YR_WATER_IND_m1) as &LOB._PREV_3YR_WATER_IND_SE
		,Coalesce(t2.PREV_4YR_CLAIM_CNT_0,t2.PREV_4YR_CLAIM_CNT_m1) as &LOB._PREV_4YR_CLAIM_CNT_SE
		,Coalesce(t2.PREV_4YR_LOSS_AMT_0,t2.PREV_4YR_LOSS_AMT_m1) as &LOB._PREV_4YR_LOSS_AMT_SE
		,Coalesce(t2.PREV_4YR_PRM_AMT_0,t2.PREV_4YR_PRM_AMT_m1) as &LOB._PREV_4YR_PRM_AMT_SE
		,Coalesce(t2.PREV_5YR_CLAIM_CNT_0,t2.PREV_5YR_CLAIM_CNT_m1) as &LOB._PREV_5YR_CLAIM_CNT_SE
		,Coalesce(t2.PREV_5YR_LOSS_AMT_0,t2.PREV_5YR_LOSS_AMT_m1) as &LOB._PREV_5YR_LOSS_AMT_SE
		,Coalesce(t2.PREV_5YR_PRM_AMT_0,t2.PREV_5YR_PRM_AMT_m1) as &LOB._PREV_5YR_PRM_AMT_SE
		,Coalesce(t2.TOT3YR_CLAIMCNT_CLOSE_NOPMT_0,t2.TOT3YR_CLAIMCNT_CLOSE_NOPMT_m1) as &LOB._TOT3YRClmCNT_CLOSENoPmt_SE
		,Coalesce(t2.PREV_NB_PRM_AMT_0,t2.PREV_NB_PRM_AMT_m1) as &LOB._PREV_NB_PRM_AMT_SE
		,Coalesce(t2.PREVAIL_CNTS_DED_0,t2.PREVAIL_CNTS_DED_m1) as &LOB._PREVAIL_CNTS_DED_SE
		,Coalesce(t2.PREVAIL_FIRE_PROT_CLS_0,t2.PREVAIL_FIRE_PROT_CLS_m1) as &LOB._PREVAIL_FIRE_PROT_CLS_SE
		,Coalesce(t2.PREVAIL_POLICY_TYPE_0,t2.PREVAIL_POLICY_TYPE_m1) as &LOB._PREVAIL_POLICY_TYPE_SE
		,Coalesce(t2.PREVAIL_SINGLE_LIMIT_0,t2.PREVAIL_SINGLE_LIMIT_m1) as &LOB._PREVAIL_SINGLE_LIMIT_SE
		,Coalesce(t2.RISK_TYPE_0,t2.RISK_TYPE_m1) as &LOB._RISK_TYPE_SE
		,Coalesce(t2.rpd,t2.rpd_m1) as &LOB._rpSE
		,Coalesce(t2.STATE_CDS_0,t2.STATE_CDS_m1) as &LOB._STATE_CDS_SE
		,Coalesce(t2.STATE_CNT_0,t2.STATE_CNT_m1) as &LOB._STATE_CNT_SE
		,Coalesce(t2.TOT_5YR_CLAIM_CNT_0,t2.TOT_5YR_CLAIM_CNT_m1) as &LOB._TOT_5YR_CLAIM_CNT_SE
		,Coalesce(t2.TOT_GL_PRM_RATIO_0,t2.TOT_GL_PRM_RATIO_m1) as &LOB._TOT_GL_PRM_RATIO_SE
		,Coalesce(t2.TOT3YR_CLAIMCNT_CLOSE_NOPMT_0,t2.TOT3YR_CLAIMCNT_CLOSE_NOPMT_m1) as &LOB._3YRCLAIMCNT_CLOSE_NOPMT_SE
		,Coalesce(t2.UCC_RATIO_0,t2.UCC_RATIO_m1) as &LOB._UCC_RATIO_SE
		,Coalesce(t2.ZERO_TRADE_CNT_0,t2.ZERO_TRADE_CNT_m1) as &LOB._ZERO_TRADE_CNT_SE

		,Coalesce(t2.NONPAYCANCEL_CNT_PREV1_0,t2.NONPAYCANCEL_CNT_PREV1_m1) as &LOB._NPC_CNT_PREV1_SE
		,Coalesce(t2.NONPAYCANCEL_CNT_PREV2_0,t2.NONPAYCANCEL_CNT_PREV2_m1) as &LOB._NPC_CNT_PREV2_SE
		,Coalesce(t2.NONPAYCANCEL_CNT_PREV3_0,t2.NONPAYCANCEL_CNT_PREV3_m1) as &LOB._NPC_CNT_PREV3_SE
		,Coalesce(t2.NBR_MO_IN_CINCIBILL_PREV1_0,t2.NBR_MO_IN_CINCIBILL_PREV1_m1) as &LOB._NBR_MO_CINCIBILL_PREV1_SE
		,Coalesce(t2.NBR_MO_IN_CINCIBILL_PREV2_0,t2.NBR_MO_IN_CINCIBILL_PREV2_m1) as &LOB._NBR_MO_CINCIBILL_PREV2_SE
		,Coalesce(t2.NBR_MO_IN_CINCIBILL_PREV3_0,t2.NBR_MO_IN_CINCIBILL_PREV3_m1) as &LOB._NBR_MO_CINCIBILL_PREV3_SE
		,Coalesce(t2.PMT_CNT_PREV1_0,t2.PMT_CNT_PREV1_m1) as &LOB._PMT_CNT_PREV1_SE
		,Coalesce(t2.PMT_CNT_PREV2_0,t2.PMT_CNT_PREV2_m1) as &LOB._PMT_CNT_PREV2_SE
		,Coalesce(t2.PMT_CNT_PREV3_0,t2.PMT_CNT_PREV3_m1) as &LOB._PMT_CNT_PREV3_SE
		

		from tmp_&LOB._master_data_2 as t1
		left join my_mosum.&LOB._se_vars as t2
			 on t1.cfxmlid = t2.cfxmlid
		order by t1.cfxmlid
	; quit;

%MEnd Merge2_MoSum;

%Merge2_MoSum(Prop);
%Merge2_MoSum(GL);


Proc Datasets Nolist;
	Delete 	TMP_PROP_MASTER_DATA_2
			TMP_GL_MASTER_DATA_2
			;
Run;
